@extends('main-website.components.master')

@section('content')

@include('main-website.components.hader')
@include('main-website.components.slider')
@include('main-website.components.feature')
@include('main-website.components.welcom')
@include('main-website.components.service')
@include('main-website.components.students')
@include('main-website.components.course')
@include('main-website.components.cat')
@include('main-website.components.institude')
@include('main-website.components.test')
@include('main-website.components.price')
@include('main-website.components.gallery')
@include('main-website.components.news')
@include('main-website.components.footer')
@include('main-website.components.serch')
@include('main-website.components.page')
@endsection